### ISSUE TITLE
Works for all IE but IE9

### ISSUE THREAD

**Issue by jeerbl** [sunflowerdeath/webfonts-generator#31]
Hi there,

I noticed the CSS generated by `webfonts-generator` does not include a fix for IE9 compat mode. As suggested in [this SO answer](https://stackoverflow.com/a/16711040/2418066), not only the `?iefix` is needed but also a `src` only having the EOT font URL:

```css
@font-face {
    font-family: 'MyWebFont';
    src: url('webfont.eot'); /* IE9 Compat Modes */
    src: url('webfont.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
         url('webfont.woff') format('woff'), /* Modern Browsers */
         url('webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
         url('webfont.svg#svgFontName') format('svg'); /* Legacy iOS */
}
```

Could you test it out? Or tell me a version I can use myself to test it ;)

Thanks!
Jerome
